version: "3"

services:
  # client:
  #   image: node:lts
  #   container_name: demo-client
  #   restart: on-failure
  #   volumes: 
  #   - ../client:/app
  #   working_dir: /app
  #   command: [ "npm", "run", "dev" ]
  #   ports: 
  #   - "3000:3000"

  api:
    image: node:lts
    container_name: demo-api
    restart: on-failure
    depends_on: 
    - db
    - waveman
    environment: 
      PORT: "8080"
      VERSION: 0.0.0-dev
      MONGOURL: mongodb://demo-mongodb:27017
      WAVE_ENDPOINT: 'http://waveman:8083'
      PICASSO_ENDPOINT: 'http://picasso:8085/palette/3'
      API_ENDPOINT: 'http://localhost:8080/api/v1/demo'
      DB: demo
      TOKEN: demotoken
    volumes: 
    - ../api:/app
    working_dir: /app
    command: 
    - node
    - --inspect=0.0.0.0
    - index.js 
    ports: 
    - "8080:8080"
    - "9229:9229"

  watchdog:
    # build: ../watchdog
    image: node:lts
    container_name: demo-watchdog
    restart: on-failure
    environment: 
      VOLUME: /app/files
      PUBLIC_PATH: '{"prefix": "http", "hostname": "localhost:8084", "dir": ""}'
      TOKEN: demotoken
      API_ENDPOINT: 'http://api:8080/api/v1/demo'
      VERSION: 0.0.0-dev
    volumes:
    - ./files:/app/files
    - ../watchdog:/app
    working_dir: /app
    command:
    - node
    - --inspect=0.0.0.0
    - index.js 
    ports:
    - "8082:8080"
    - "9230:9229"

  waveman:
    build:
      context: ../waveman
      dockerfile: Dockerfile
    container_name: demo-wave-man
    restart: on-failure
    environment:
      VERSION: 0.0.0-dev
    volumes: 
    - ../waveman/config:/app/config
    - ./files:/app/files
    ports:
    - "8083:8083"

  picasso:
    build:
      context: ../picasso
      dockerfile: Dockerfile
    container_name: demo-picasso
    restart: on-failure
    environment:
      VOLUME: /app/files/
      VERSION: 0.0.0-dev
    volumes:
    - ./files:/app/files
    ports:
    - "8085:8085"

  db:
    image: mongo:4.2.5
    container_name: demo-mongodb
    restart: on-failure
    volumes:
    - db-data:/data/db
    environment: 
      MONGO_INITDB_DATABASE: demo
    ports:
    - "27017:27017"

  fileserver:
    image: nginx:alpine
    container_name: demo-fileserver
    restart: on-failure
    volumes:
    - ./files:/usr/share/nginx/html
    ports:
    - "8084:80"

volumes:
  db-data: