apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-man-waveman-config
  namespace: web
  labels:
    app: demo-man
    svc: waveman
data:
  config.json: |
    {
      "full": {
        "step_width": 20,
        "height": 200,
        "rounded": 10,
        "steps": 50,
        "gap": 10
      },
      "small": {
        "step_width": 20,
        "height": 200,
        "rounded": 10,
        "steps": 25,
        "gap": 10
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-man-fileserver-nginx-config
  namespace: web
data:
  files-zoomoid-de.conf: |
    server {
        server_name demo.zoomoid.de;
        root /var/www/demo;
        location /files {
            autoindex on;
            sendfile on;
            sendfile_max_chunk 1m;
            tcp_nopush on;
            tcp_nodelay on;
            keepalive_timeout 65;
        }
        listen 80;
        # listen [::]:80 ipv6only=true;
    }
