apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-mongodb-pvc
  namespace: web
  labels:
    app: demo-man
    svc: mongodb
spec:
  storageClassName: kadalu.replica1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-audio-pvc
  namespace: web
  labels:
    app: demo-man
    svc: watchdog
spec:
  storageClassName: kadalu.replica1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
    limits:
      storage: 5Gi